apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hrva
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hrva
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hrva
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hrva
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hrva
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-znrc-tenant/rhtap-demo-app/hacbs-test-project-hrva@sha256:8787e72f19bcb72fd5728312325d91aef09b4a58ccfc7beb9444403c6a4a18bf
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
