apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-hrva
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-znrc-tenant/rhtap-demo-app/hacbs-test-project-hrva@sha256:8787e72f19bcb72fd5728312325d91aef09b4a58ccfc7beb9444403c6a4a18bf
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
